# Generated by Django 5.2.17 on 2026-09-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='analysis_model',
            field=models.CharField(default='gemma-4-26b-a4b-it', max_length=80),
        ),
        migrations.AddField(
            model_name='organization',
            name='auto_analyze_tickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='require_agent_approval',
            field=models.BooleanField(default=True),
        ),
    ]
