# Generated by Django 5.2.17 on 2026-09-27 15:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#64748B', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a six-digit hexadecimal color such as #64748B.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('waiting', 'Waiting'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('source', models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('api', 'API'), ('agent', 'AI Agent')], default='web', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tickets.comment')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_ticket_tags', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tags', to='tickets.tag')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tags', to='tickets.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tickets', through='tickets.TicketTag', to='tickets.tag'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['organization', 'name'], name='tag_org_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_tag_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['ticket', 'created_at'], name='comment_ticket_created_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-created_at'], name='comment_author_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='comment_body_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='tickettag',
            constraint=models.UniqueConstraint(fields=('ticket', 'tag'), name='unique_tag_per_ticket'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='ticket_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organization', 'priority', '-created_at'], name='ticket_org_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organization', 'assignee', 'status'], name='ticket_org_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['customer', '-created_at'], name='ticket_customer_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='ticket_version_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', False), ('status__in', ['resolved', 'closed'])), models.Q(models.Q(('status__in', ['resolved', 'closed']), _negated=True), ('resolved_at__isnull', True)), _connector='OR'), name='ticket_resolution_timestamp_matches_status'),
        ),
    ]
