# Generated by Django 5.2.17 on 2026-09-27 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=120)),
                ('source_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('url', 'URL')], default='text', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_documents', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='organizations.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['organization', 'status', '-updated_at'], name='doc_org_status_idx'), models.Index(fields=['organization', 'title'], name='doc_org_title_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'slug'), name='unique_document_slug_per_org'), models.UniqueConstraint(condition=models.Q(('checksum', ''), _negated=True), fields=('organization', 'checksum'), name='unique_document_checksum_per_org')],
            },
        ),
    ]
