# Generated by Django 5.2.17 on 2026-09-27 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('bug', 'Bug'), ('feature_request', 'Feature request'), ('billing', 'Billing'), ('general_inquiry', 'General inquiry')], max_length=30)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=20)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('suggested_tags', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(blank=True, max_length=40)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='organizations.organization')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status', '-created_at'], name='analysis_org_status_idx'), models.Index(fields=['ticket', '-created_at'], name='analysis_ticket_created_idx'), models.Index(fields=['organization', 'category', '-created_at'], name='analysis_org_category_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', False), ('status__in', ['completed', 'failed'])), models.Q(models.Q(('status__in', ['completed', 'failed']), _negated=True), ('finished_at__isnull', True)), _connector='OR'), name='analysis_finish_time_matches_status')],
            },
        ),
    ]
