# Generated by Django 5.2.17 on 2026-09-27 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('entity_type', models.CharField(choices=[('organization', 'Organization'), ('membership', 'Membership'), ('user', 'User'), ('customer', 'Customer'), ('ticket', 'Ticket'), ('comment', 'Comment'), ('tag', 'Tag'), ('knowledge_document', 'Knowledge document'), ('ai_analysis', 'AI analysis')], max_length=40)),
                ('entity_id', models.UUIDField()),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_org_created_idx'), models.Index(fields=['organization', 'entity_type', 'entity_id'], name='audit_entity_idx'), models.Index(fields=['actor', '-created_at'], name='audit_actor_created_idx'), models.Index(fields=['organization', 'action', '-created_at'], name='audit_org_action_idx')],
            },
        ),
    ]
